package ext

// Code generated by exporter-builder. DO NOT EDIT.

func init() {
	RegisterCapability(CapabilityInfo{
		Name:           "authtest",
		Kind:           CapabilityKind("security"),
		Version:        "1.0.0",
		Description:    "authtest capability package",
		Owner:          "security",
		ImportPath:     "example.com/exporter/custom/capabilities/authtest",
		Source:         "custom/capabilities/authtest",
		DefaultEnabled: false,
		Provides:       []string{"security:authtest"},
		Requires:       []string{},
		Metrics:        []string{},
		Config:         map[string]string{},
		Compatible:     CompatibleRange{Exporters: []string{"*"}},
		Files:          []string{"custom/capabilities/authtest/capability.go"},
	})
}
