const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");

const root = process.cwd();
const modulePath = "example.com/exporter";
const manifestPath = path.join(root, "custom", "custom.yaml");

const manifest = fs.readFileSync(manifestPath, "utf8");
const packages = parsePackages(manifest).filter((pkg) => pkg.enabled !== false);

const infos = packages.map((pkg) => {
  const sourceDir = `custom/capabilities/${pkg.name}`;
  const sourceFile = `${sourceDir}/capability.go`;
  return {
    name: pkg.name,
    kind: pkg.kind,
    version: "1.0.0",
    description: `${pkg.name} capability package`,
    owner: ownerFor(pkg.kind),
    importPath: `${modulePath}/${sourceDir}`,
    source: sourceDir,
    defaultEnabled: false,
    provides: [`${pkg.kind}:${pkg.name}`],
    requires: [],
    metrics: [],
    config: {},
    compatible: { exporters: ["*"], minVersion: "", maxVersion: "" },
    files: [sourceFile],
    checksum: checksumIfExists(path.join(root, sourceFile))
  };
});

writeFile("custom/all/all_gen.go", renderAllGen(infos));
writeFile("company/ext/capabilities_gen.go", renderCapabilitiesGen(infos));
writeFile("custom/custom.lock.yaml", renderLock(infos));
writeFile("dist/build-info.json", JSON.stringify({
  builder: "exporter-builder",
  schemaVersion: "v1",
  modulePath,
  stableHook: "company/ext/registry.go:RegisterCompanyExt",
  mainHookImport: `_ "${modulePath}/custom/all"`,
  inputs: ["custom/custom.yaml"],
  generatedFiles: [
    "custom/all/all_gen.go",
    "company/ext/capabilities_gen.go",
    "custom/custom.lock.yaml",
    "dist/build-info.json"
  ],
  selectedPackages: infos.map((info) => info.name),
  generatedAt: new Date().toISOString()
}, null, 2));

console.log(`generated ${infos.length} capability package(s)`);

function parsePackages(text) {
  const result = [];
  let current = null;
  for (const line of text.split(/\r?\n/)) {
    const name = line.match(/^\s*-\s+name:\s*([a-zA-Z0-9_-]+)/);
    if (name) {
      current = { name: name[1], enabled: true };
      result.push(current);
      continue;
    }
    if (!current) continue;
    const kind = line.match(/^\s+kind:\s*([a-zA-Z0-9_-]+)/);
    if (kind) current.kind = kind[1];
    const enabled = line.match(/^\s+enabled:\s*(true|false)/);
    if (enabled) current.enabled = enabled[1] === "true";
  }
  return result.filter((pkg) => pkg.name && pkg.kind);
}

function renderAllGen(infos) {
  return `package all

// Code generated by exporter-builder. DO NOT EDIT.

import (
${infos.map((info) => `\t_ "${info.importPath}"`).join("\n")}
)
`;
}

function renderCapabilitiesGen(infos) {
  return `package ext

// Code generated by exporter-builder. DO NOT EDIT.

func init() {
${infos.map((info) => `\tRegisterCapability(CapabilityInfo{
\t\tName:           "${info.name}",
\t\tKind:           CapabilityKind("${info.kind}"),
\t\tVersion:        "${info.version}",
\t\tDescription:    "${info.description}",
\t\tOwner:          "${info.owner}",
\t\tImportPath:     "${info.importPath}",
\t\tSource:         "${info.source}",
\t\tDefaultEnabled: ${info.defaultEnabled},
\t\tProvides:       []string{${info.provides.map((item) => `"${item}"`).join(", ")}},
\t\tRequires:       []string{${info.requires.map((item) => `"${item}"`).join(", ")}},
\t\tMetrics:        []string{${info.metrics.map((item) => `"${item}"`).join(", ")}},
\t\tConfig:         map[string]string{},
\t\tCompatible:     CompatibleRange{Exporters: []string{"*"}},
\t\tFiles:          []string{${info.files.map((item) => `"${item}"`).join(", ")}},
\t})`).join("\n")}
}
`;
}

function renderLock(infos) {
  return [
    "schemaVersion: v1",
    "generated_by: exporter-builder",
    `generated_at: ${new Date().toISOString()}`,
    "packages:",
    ...infos.flatMap((info) => [
      `  - name: ${info.name}`,
      `    kind: ${info.kind}`,
      `    version: ${info.version}`,
      `    import_path: ${info.importPath}`,
      `    source: ${info.source}`,
      `    checksum: ${info.checksum}`
    ])
  ].join("\n") + "\n";
}

function writeFile(relativePath, content) {
  const target = path.join(root, relativePath);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, content, "utf8");
}

function checksumIfExists(file) {
  if (!fs.existsSync(file)) return "missing";
  return crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex");
}

function ownerFor(kind) {
  if (kind === "security" || kind === "credential_provider") return "security";
  return "network-ops";
}
